// Mocks generated by Mockito 5.4.4 from annotations
// in user_identification/test/presentation/pages/identification_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:ui_kit/ui_kit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i2.NotificationService {
  @override
  void showMessage({
    required String? message,
    _i2.NotificationType? type = _i2.NotificationType.info,
    Duration? duration = const Duration(seconds: 3),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showMessage,
          [],
          {
            #message: message,
            #type: type,
            #duration: duration,
          },
        ),
        returnValueForMissingStub: null,
      );
}
