name: vehicle_selection
description: Vehicle selection module for the CarOnSale app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core package for shared utilities
  core:
    path: ../../core
  
  # UI kit package for shared UI components
  ui_kit:
    path: ../../ui_kit
  
  # State management
  flutter_bloc: ^8.1.3
  
  # Functional programming
  dartz: ^0.10.1
  
  # HTTP client
  http: ^1.1.0
  
  # Utilities
  equatable: ^2.0.5
  
  # Local storage
  shared_preferences: ^2.2.0
  
  # Routing
  go_router: ^10.1.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true