name: core
description: Core utilities and shared code for the CarOnSale app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_bloc: ^8.1.3
  
  # Functional programming
  dartz: ^0.10.1
  
  # Dependency injection
  get_it: ^7.6.0
  
  # HTTP client for network calls
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.0
  
  # Utilities
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true